POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mary Kenneth Keller",
    "number": "1234556"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mary Kenneth Keller",
    "number": "1-22334455"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mary Kenneth Keller",
    "number": "10-22-334455"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mary Kenneth Keller",
    "number": "1a22334455"
}